# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://sanketloke.github.io/
baseurl: /
title: Sanket Lokegaonkar
author: Sanket Lokegaonkar
description: Personal blog and resume
avatar: profile.png
email: sloke@vt.edu
github: sanketloke # username
twitter: sanketloke94
linkedin: sanketloke
stackoverflow: users/4380063/sloke
facebook: sanket.lokegaonkar   #e.g: users/4380063/sloke
#Comment out if you don't want disqus 
#disqus: username
google_analytics: UA-99360899-1


# needed for travis-ci build
exclude: [vendor]
